server:
  port: 8080
  max-http-header-size: 65536
  tomcat:
    accesslog:
      enabled: true
#  servlet:
#    context-path: /api/v1
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: openapi
          uri: http://localhost:${server.port}/
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: onboard-service
          uri: lb://ONBOARD-SERVICE
#          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/cities/**
#          filters:
#            - name: CircuitBreaker
        - id: payment-service
          #uri: lb:PAYMENT-SERVICE
          uri: http://localhost:8082/
          predicates:
            - Path=/payment/**
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


#spring:
#  application:
#    name: GATEWAY-SERVICE
#  cloud:
#    gateway:
#      routes:
#        - id: onboard-service
#          uri: lb:ONBOARD-SERVICE
#          predicates:
#            - Path=/cities/**
#
#        - id: payment-service
#          uri: lb:PAYMENT-SERVICE
#          predicates:
#            - Path=/payment/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

springdoc:
  packagesToScan: com.arpangroup.onboarding.controller